import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { initializeApp } from "firebase/app";
import { getFirestore, doc, setDoc, addDoc, collection, getDocs } from "firebase/firestore";
import { useRef, useState } from 'react';

export default function Home() {

  // ******************firebase

  // Import the functions you need from the SDKs you need
  // TODO: Add SDKs for Firebase products that you want to use
  // https://firebase.google.com/docs/web/setup#available-libraries

  // Your web app's Firebase configuration
  const firebaseConfig = {
    apiKey: "AIzaSyAltwmLRlHaaSfzO9Vsqy8ByR9htFbQnHo",
    authDomain: "chatbot-demo-6cf0c.firebaseapp.com",
    databaseURL: "https://chatbot-demo-6cf0c-default-rtdb.firebaseio.com",
    projectId: "chatbot-demo-6cf0c",
    storageBucket: "chatbot-demo-6cf0c.appspot.com",
    messagingSenderId: "613545308774",
    appId: "1:613545308774:web:2c3b8dad384a5acff9f3a7"
  };

  // Initialize Firebase
  const app = initializeApp(firebaseConfig);
  const db = getFirestore(app);
  // ***************firebaseここまで
  const ref = useRef();
  const [getData,setGetData]=useState([]);

  // ----------------firebase データ追加テスト

  const dataPusher = async () => {
    await addDoc(collection(db, "posts"), {
      post: ref.current.value
    });
    ref.current.value=('');
  }

  const dataGetter = async () => {
    setGetData(['']);
    const querySnapshot = await getDocs(collection(db, "posts"));
    querySnapshot.forEach((doc) => {
      setGetData((indata)=>[...indata,doc.data().post]);
    });
    console.log(getData);
  }
  // ----------------firebase データ追加テストここまで



  return (
    <div className={styles.container}>
      <Head>
        <title>Fighting App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>JLN902-スチールプランテック</h1>
      <h2>必要事項管理表</h2>
      <input ref={ref} type="text" />
      <button onClick={dataPusher}>登録ボタン</button>
      <button onClick={dataGetter}>読込ボタン</button>
      {getData.map((data,index)=>(
        <div key={index}>
          {data}
        </div>
      ))}
    </div>
  )
}
